name: test-and-connect-publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
 
jobs:
  test-and-connect-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
          
      - name: Test Shiny App
        shell: Rscript {0}
        run: |
          shinytest2::test_app()
        continue-on-error: true
          
      - name: Create manifest.json
        shell: Rscript {0}
        run: |
          rsconnect::writeManifest()

      - name: Download content using curl
        run: |
            # Use curl to download content from your server and save it to a file
            curl -L -H "Authorization: Bearer ${{ secrets.CONNECT_API_KEY }}" -o /tmp/your-content.html ${{ secrets.CONNECT_SERVER }}/phddmmpy/

      - name: Upload downloaded content as artifact
        uses: actions/upload-artifact@v3
        with:
            name: downloaded-content
            path: /tmp/your-content.html

